name: PHP TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test_7_1:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:7.1
    steps:
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.1.xml
  test_7_2:
    runs-on: self-hosted
    container: babadzhanyan/php-unit:7.2
    steps:
      - name: Install dependencies
        run: composer install --prefer-install=auto --no-interaction
      - name: Run Tests
        run: php vendor/bin/phpunit --coverage-text --colors=never -c phpunit_7.2.xml
